version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pass*56964
      MYSQL_DATABASE: mySQL
    ports:
      - "3306:3306"

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
